spring:
  application:
    name: greeting-service
  config:
    import: optional:configserver:http://localhost:8888/
  cloud:
    config:
      profile: dev
greeting-service:
  greeting: "Olá"
  default-value: "Mundo"